#!/usr/bin/env bash
set -eo pipefail

SCRIPTS="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$(dirname "$SCRIPTS")" && pwd)"

"$SCRIPTS/mksecrets" "$@"
nix build \
  --extra-experimental-features nix-command \
  --extra-experimental-features flakes \
  "path:${ROOT}#nixosConfigurations.pidgeon.config.system.build.sdImage"
