#!/usr/bin/env bash
set -eou pipefail

SCRIPTS="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$(dirname "$SCRIPTS")" && pwd)"
cd "$ROOT"

cargo-clippy --allow-dirty
ruff check .
shellcheck "$SCRIPTS"/*
prettier --check .
