#!/usr/bin/env bash
set -eo pipefail

SCRIPTS="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$(dirname "$SCRIPTS")" && pwd)"
SECRETS="$ROOT/secrets"
mkdir -p "$SECRETS"
SYSTEM_SECRETS="$ROOT/src/system/secrets"
mkdir -p "$SYSTEM_SECRETS"
TMP_SECRETS="$SECRETS/tmp"
mkdir -p "$TMP_SECRETS"

openssl rand -hex 16 >"$SECRETS/id.txt"
ID="$(cat "$SECRETS/id.txt")"
mkdir -p "$SECRETS/$ID"
cp "$SECRETS/id.txt" "$SECRETS/$(cat "$SECRETS/id.txt")/id.txt"
cp "$SECRETS/id.txt" "$SYSTEM_SECRETS/id.txt"

mktmp() {
  local name

  name="$1"

  cp "$SECRETS/$ID/$name" "$TMP_SECRETS/$name"
  cp "$SECRETS/$ID/$name" "$SYSTEM_SECRETS/$name"
}

mkid() {
  local name

  name="$1"

  openssl rand -base64 32 >"$SECRETS/$ID/$name"
}

mkage() {
  local path

  name="$1"

  age-keygen -o "$SECRETS/$ID/$name.key" 2>&1 |
    awk '{ print $3 }' >"$SECRETS/$ID/$name.pub"
}

mkssh() {
  local name
  local comment

  if [[ "x$2" == "x" ]]; then
    name="$1"

    ssh-keygen -q -a 100 -t ed25519 -N "" \
      -f "$SECRETS/$ID/$name"
  else
    name="$1"
    comment="$2"

    ssh-keygen -q -a 100 -t ed25519 -N "" \
      -C "$comment" \
      -f "$SECRETS/$ID/$name"
  fi
}

mkssl() {
  local name
  local ca
  local subj

  if [[ "x$3" == "x" ]]; then
    name="$1"
    subj="$2"

    openssl genpkey -algorithm ED25519 \
      -out "$SECRETS/$name.key" >/dev/null 2>&1
    openssl req -x509 \
      -key "$SECRETS/$name.key" \
      -out "$SECRETS/$name.crt" \
      -subj "/CN=$subj" \
      -days 3650 >/dev/null 2>&1
  else
    name="$1"
    ca="$2"
    subj="$3"

    openssl genpkey -algorithm ED25519 \
      -out "$SECRETS/$ID/$name.key" >/dev/null 2>&1
    openssl req -new \
      -key "$SECRETS/$ID/$name.key" \
      -out "$SECRETS/$ID/$name.csr" \
      -subj "/CN=$subj" >/dev/null 2>&1
    openssl x509 -req \
      -in "$SECRETS/$ID/$name.csr" \
      -CA "$ca.crt" \
      -CAkey "$ca.key" \
      -CAcreateserial \
      -out "$SECRETS/$ID/$name.crt" \
      -days 3650 >/dev/null 2>&1
  fi
}

indent() {
  local text
  local amount

  text="$1"
  amount="$2"

  printf "%b" "$text" |
    sed -z "s/\\n/,/g;s/,/\\n$(printf "%${amount}s" "")/g"
}

mkid "api.key"
mkid "password.key"
mktmp "password.key"

mkage "pidgeon-age"
mktmp "pidgeon-age.key"
mkage "secrets-age"
mkssh "authorized" "pidgeon-$ID authorized"
mktmp "authorized.pub"

if [[ ! -f "$SECRETS/root.key" ]]; then
  mkssl "root" "OZDS Root CA"
fi
mkssl "ca" "$SECRETS/root" "pidgeon-$ID CA"
mkssl "postgres" "$SECRETS/$ID/ca" "pidgeon-$ID postgres"

mkid "postgres-postgres.key"
mkid "postgres-pidgeon.key"
cat >"$SECRETS/$ID/passwords.sql" <<EOF
ALTER USER postgres WITH PASSWORD '$(cat "$SECRETS/$ID/postgres-postgres.key")';
ALTER USER pidgeon WITH PASSWORD '$(cat "$SECRETS/$ID/postgres-pidgeon.key")';
EOF

cat >"$SECRETS/$ID/.env" <<EOF
PIDGEON_CLOUD_SSL="1"
PIDGEON_CLOUD_DOMAIN="TODO"
PIDGEON_CLOUD_API_KEY="$(cat "$SECRETS/$ID/api.key")"
PIDGEON_CLOUD_ID="$ID"

PIDGEON_DB_DOMAIN="localhost"
PIDGEON_DB_USER="pidgeon"
PIDGEON_DB_PASSWORD="$(cat "$SECRETS/$ID/postgres-pidgeon.key")"
PIDGEON_DB_NAME="pidgeon"

PIDGEON_NETWORK_IP_RANGE_START="192.168.1.0"
PIDGEON_NETWORK_IP_RANGE_END="192.168.1.255"
EOF

cat >"$SECRETS/$ID/secrets.yaml" <<EOF
.env: |
  $(indent "$(cat "$SECRETS/$ID/.env")" 2)
ca.key: |
  $(indent "$(cat "$SECRETS/$ID/ca.key")" 2)
ca.crt: |
  $(indent "$(cat "$SECRETS/$ID/ca.crt")" 2)
postgres.key: |
  $(indent "$(cat "$SECRETS/$ID/postgres.key")" 2)
postgres.crt: |
  $(indent "$(cat "$SECRETS/$ID/postgres.crt")" 2)
paswords.sql: |
  $(indent "$(cat "$SECRETS/$ID/passwords.sql")" 2)
EOF

sops --encrypt \
  --age "$(
    printf "%s,%s" \
      "$(cat "$SECRETS/$ID/pidgeon-age.pub")" \
      "$(cat "$SECRETS/$ID/secrets-age.pub")"
  )" \
  "$SECRETS/$ID/secrets.yaml" >"$SECRETS/$ID/secrets.enc.yaml"
mktmp "secrets.enc.yaml"
